[package]
name = "processmanager"
version = "0.1.0"
edition = "2021"
authors = ["Marc Riegel <mail@mrcrgl.de>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/mrcrgl/processmanager-rs"
categories = ["rust-patterns"]
keywords = ["process", "graceful-shutdown", "signal", "runnable"]


[dependencies]
async-trait = "0.1"
futures = "0.3"
signal-hook = "0.3"
signal-hook-tokio = { version = "0.3", features = ["futures-v0_3"] }
thiserror = "1"
tokio = { version = "1", features = ["full"] }
